import { useState } from "react";
import PropTypes from "prop-types";
import { Link } from "react-router-dom";
import { HiArrowUpRight, HiOutlineChartBar, HiOutlineMap, HiOutlineSquares2X2, HiOutlineDocumentText, HiOutlineMicrophone } from "react-icons/hi2";
import PublicHeader from "../components/common/PublicSite/PublicHeader";
import PublicFooter from "../components/common/PublicSite/PublicFooter";
import HeroVideo from "../components/common/PublicSite/HeroVideo";
import Newsletter from "../components/Homepage/Newsletter";
import { operationalStates } from "../data/operationalStates";
import { newsStories, newsResources } from "../data/newsContent";
import "./NewsPage.css";

function NewsHeading({ eyebrow, title, text, to, action }) {
  return <header className="news-heading"><div><p className="coral-eyebrow"><span />{eyebrow}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>{to && <Link to={to}>{action}<HiArrowUpRight aria-hidden="true" /></Link>}</header>;
}
NewsHeading.propTypes = { eyebrow: PropTypes.string.isRequired, title: PropTypes.string.isRequired, text: PropTypes.string, to: PropTypes.string, action: PropTypes.string };

function NewsCard({ item }) {
  return <article className="news-card">{item.image && <Link to={item.to} tabIndex={-1} aria-hidden="true"><img src={item.image} alt="" loading="lazy" /></Link>}<div><p className="news-label">{item.category}</p><h3><Link to={item.to}>{item.title}</Link></h3><p>{item.text}</p><Link className="news-link" to={item.to}>{item.action}<HiArrowUpRight aria-hidden="true" /></Link></div></article>;
}
NewsCard.propTypes = { item: PropTypes.shape({ category: PropTypes.string.isRequired, title: PropTypes.string.isRequired, text: PropTypes.string.isRequired, image: PropTypes.string, to: PropTypes.string.isRequired, action: PropTypes.string.isRequired }).isRequired };

function NewsBanner({ eyebrow, title, text, image, to, action }) {
  return <section className="news-banner"><img src={image} alt="" loading="lazy" /><div className="coral-shell"><div><p className="coral-eyebrow"><span />{eyebrow}</p><h2>{title}</h2><p>{text}</p></div><Link className="coral-button coral-button--primary" to={to}>{action}<HiArrowUpRight aria-hidden="true" /></Link></div></section>;
}
NewsBanner.propTypes = { eyebrow: PropTypes.string.isRequired, title: PropTypes.string.isRequired, text: PropTypes.string.isRequired, image: PropTypes.string.isRequired, to: PropTypes.string.isRequired, action: PropTypes.string.isRequired };

export default function NewsPage() {
  const [active, setActive] = useState(0);
  const story = newsStories[active];
  return <main className="coral-inner-page news-page"><PublicHeader />
    <section className="news-hero" aria-labelledby="news-title"><HeroVideo src="/hero_bg.mp4" poster="/coral/coral-mine-hero.png" /><div className="coral-shell news-hero__copy"><p className="coral-eyebrow"><span />News & insights</p><h1 id="news-title">Perspectives from<br /><em>a changing industry.</em></h1><p>Explore the ideas, operational perspectives and conversations shaping Coral’s approach to responsible mining.</p><div className="news-actions"><a className="coral-button coral-button--primary" href="#news-stories">Explore our stories <HiArrowUpRight aria-hidden="true" /></a><Link className="coral-button coral-button--ghost" to="/reports">Reports & publications <HiArrowUpRight aria-hidden="true" /></Link></div></div><div className="coral-shell news-hero__bottom"><span>Mine / Move / Restore</span><a href="#news-data">Discover more ↓</a></div></section>
    <nav className="news-nav" aria-label="News sections"><div className="coral-shell">{[["Data & dashboards", "news-data"], ["Stories", "news-stories"], ["Research & resources", "news-research"], ["Toolkit", "news-toolkit"], ["Videos", "news-videos"], ["Regional facts", "news-facts"]].map(([label, id]) => <a key={id} href={`#${id}`}>{label}</a>)}</div></nav>
    <section className="news-section coral-shell" id="news-data"><NewsHeading eyebrow="Dashboards & data" title="See the bigger picture." text="Explore the network, capabilities and operating tools behind Coral." /><div className="news-grid">{[{ icon: HiOutlineChartBar, title: "Operations dashboard", text: "Explore the operational overview and regional coverage.", to: "/dashboard" }, { icon: HiOutlineMap, title: "Our regional footprint", text: "Navigate the states and districts in our mapped network.", to: "/#operational-areas" }, { icon: HiOutlineSquares2X2, title: "Integrated capabilities", text: "See how people, equipment and services connect.", to: "/capabilities" }].map(item => { const Icon = item.icon; return <article className="news-data-card" key={item.title}><Icon aria-hidden="true" /><h3>{item.title}</h3><p>{item.text}</p><Link className="news-link" to={item.to}>Explore <HiArrowUpRight aria-hidden="true" /></Link></article>; })}</div></section>
    <section className="news-feature-section" id="news-stories"><div className="coral-shell news-section"><NewsHeading eyebrow="News & perspectives" title="From the ground. In focus." text="Event announcements and perspectives on Coral’s work." /><div className="news-feature-layout"><article className="news-feature" id="featured-story" aria-live="polite" aria-atomic="true"><img src={story.image} alt="" loading="lazy" /><div><p className="news-label">{story.category}</p><h3>{story.title}</h3><p>{story.text}</p><Link className="news-link" to={story.to}>{story.action}<HiArrowUpRight aria-hidden="true" /></Link></div></article><div className="news-story-list" role="group" aria-label="Choose a featured story">{newsStories.map((item, index) => <button type="button" key={item.title} onClick={() => setActive(index)} aria-pressed={active === index} aria-controls="featured-story"><img src={item.image} alt="" loading="lazy" /><span><small>{item.category}</small><strong>{item.title}</strong><span>{active === index ? "In focus" : "View story"} <HiArrowUpRight aria-hidden="true" /></span></span></button>)}</div></div></div></section>
    <NewsBanner eyebrow="Reports & publications" title="Our work, in perspective." text="Find publication updates and contact our team for information about Coral’s operations." image="/coral/impact-land-restoration.jpg" to="/reports" action="Visit publications" />
    <section className="news-section coral-shell" id="news-research"><NewsHeading eyebrow="Research & resources" title="Explore the thinking behind the work." text="An introduction to our operating approach, equipment and environmental priorities." to="/capabilities" action="All capabilities" /><div className="news-grid">{newsResources.map(item => <NewsCard key={item.title} item={item} />)}</div></section>
    <NewsBanner eyebrow="Event spotlight · Talcher, Odisha" title="Odisha Mining Week." text="A place for conversations about mining, skills, equipment and the future of the industry. Explore the announcement on our homepage." image="/coral/coral-mine-hero.png" to="/#odisha-mining-week" action="Explore the event" />
    <section className="news-section coral-shell" id="news-toolkit"><NewsHeading eyebrow="Toolkit" title="Useful starting points." text="Find the right information for working with Coral." /><div className="news-grid">{[{ category: "Suppliers & partners", title: "Procurement guidance", text: "Review the application process, tender notices and submission guidance.", to: "/tenders", action: "View tender guidance" }, { category: "Careers", title: "Career pathways", text: "Explore our teams, early-career pathways and published opportunities.", to: "/careers", action: "Explore careers" }, { category: "Digital tools", title: "Applications & operations", text: "Access the dashboard and digital applications used across the site.", to: "/apps", action: "Explore applications" }].map(item => <NewsCard key={item.title} item={item} />)}</div></section>
    <section className="news-conversations"><div className="coral-shell"><HiOutlineMicrophone aria-hidden="true" /><div><p className="coral-eyebrow"><span />Industry conversations</p><h2>Ideas worth sharing.</h2><p>Connect with Coral about industry discussions, events and perspectives on responsible mining.</p></div><Link className="coral-button coral-button--primary" to="/contact">Start a conversation <HiArrowUpRight aria-hidden="true" /></Link></div></section>
    <section className="news-section coral-shell" id="news-videos"><NewsHeading eyebrow="Videos" title="A closer look at the landscape." text="A visual introduction to the scale and setting of mining operations." /><figure className="news-film"><video controls playsInline preload="none" poster="/coral/coral-mine-hero.png" aria-label="Illustrative mining landscape film"><source src="/hero_bg.mp4" type="video/mp4" />Your browser does not support video playback.</video><figcaption><span>Mining landscape</span><p>Illustrative footage of the mining environment.</p></figcaption></figure></section>
    <section className="news-facts" id="news-facts"><div className="coral-shell news-section"><NewsHeading eyebrow="Regional fact sheets" title="Our footprint, at a glance." text="A snapshot of the regions and districts on Coral’s operational map." to="/#operational-areas" action="Explore the full map" /><div className="news-grid">{operationalStates.map(state => <article className="news-fact-card" key={state.name}><HiOutlineDocumentText aria-hidden="true" /><p className="news-label">{state.region}</p><h3>{state.name}</h3><div className="news-fact-number"><strong>{String(state.districts.length).padStart(2, "0")}</strong><span>mapped districts</span></div><p>{state.districts.join(" · ")}</p><Link className="news-link" to="/#operational-areas">View regional map <HiArrowUpRight aria-hidden="true" /></Link></article>)}</div></div></section>
    <Newsletter /><PublicFooter /></main>;
}
