import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { HiArrowUpRight, HiOutlineDocumentText, HiOutlineEnvelope } from "react-icons/hi2";
import PublicHeader from "../components/common/PublicSite/PublicHeader";
import PublicFooter from "../components/common/PublicSite/PublicFooter";
import { OpportunityHeading, OpportunityEmpty, StatusFilter } from "../components/Opportunities/OpportunityPrimitives";
import { tenderNotices } from "../data/opportunities";
import "./Opportunities.css";

const steps = [
  ["Review the notice", "Read the scope of work, eligibility, required documents and closing date for the relevant opportunity."],
  ["Prepare your proposal", "Include the technical and commercial information requested, using the formats specified in the notice."],
  ["Submit as instructed", "Follow the submission method and delivery address in the tender document. Retain your submission acknowledgement."],
];

export default function TendersPage() {
  const archive = useLocation().pathname === "/tenders/all";
  const [status, setStatus] = useState(archive ? "All" : "Open");
  const filtered = tenderNotices.filter(notice => status === "All" || notice.status === status);
  const visible = archive ? filtered : filtered.slice(0, 4);
  return <main className="coral-inner-page op-page"><PublicHeader />
    <header className="op-tender-header"><div className="coral-shell"><p className="coral-eyebrow"><span />Procurement at Coral</p><h1>{archive ? "Tender archive." : "Work with Coral."}<br /><em>{archive ? "Every notice, in one place." : "Build a stronger supply chain."}</em></h1><p>Procurement opportunities for suppliers, contractors and service partners across our mining ecosystem.</p>{archive ? <Link className="op-inline-link" to="/tenders">← Back to tenders</Link> : <a className="op-inline-link" href="#tender-notices">Browse tender notices ↓</a>}</div></header>
    {!archive && <section className="op-section coral-shell op-procurement-intro" aria-labelledby="procurement-guide"><article className="op-guide"><p className="coral-eyebrow"><span />Supplier information</p><h2 id="procurement-guide">A clear route to participation.</h2><p>Welcome to Coral’s procurement portal. Use the guidance below to prepare for an opportunity and refer to the individual notice for its specific requirements.</p><h3>How to apply</h3><ol className="op-steps">{steps.map(([title, text], index) => <li key={title}><span>0{index + 1}</span><div><h4>{title}</h4><p>{text}</p></div></li>)}</ol><div className="op-guidance-note"><HiOutlineDocumentText aria-hidden="true" /><p>Each tender notice sets its own eligibility, deadline and submission instructions. A general enquiry does not constitute a tender submission.</p></div><div className="op-procurement-contact"><HiOutlineEnvelope aria-hidden="true" /><div><h3>Procurement enquiries</h3><p>Need help identifying the right opportunity?</p><Link to="/contact">Contact Coral <HiArrowUpRight aria-hidden="true" /></Link></div></div></article><aside className="op-updates" aria-labelledby="procurement-updates"><div className="op-section-top"><h2 id="procurement-updates">Updates & resources</h2><HiOutlineDocumentText aria-hidden="true" /></div><p>Information for prospective suppliers and service partners.</p><div className="op-update-list"><a href="#tender-notices"><small>Notices</small><h3>Current procurement opportunities</h3><p>Check open notices and their submission requirements.</p><HiArrowUpRight aria-hidden="true" /></a><Link to="/tenders/all"><small>Archive</small><h3>Previous tender notices</h3><p>Browse the complete register of published notices.</p><HiArrowUpRight aria-hidden="true" /></Link><Link to="/capabilities"><small>Working together</small><h3>Understand our capabilities</h3><p>Explore the services behind Coral’s operating model.</p><HiArrowUpRight aria-hidden="true" /></Link></div></aside></section>}
    <section className="op-band" id="tender-notices"><div className="op-section coral-shell"><div className="op-section-top"><OpportunityHeading eyebrow={archive ? "Procurement archive" : "Procurement opportunities"} title={archive ? "All tender notices" : "Tender notices"} text="Review open opportunities or browse closed notices." /><StatusFilter value={status} onChange={setStatus} options={archive ? ["All", "Open", "Closed"] : ["Open", "Closed"]} records={tenderNotices} /></div>{archive ? <div className="op-table-wrap" role="region" aria-label="Tender register" tabIndex={0}><table><caption>Coral procurement notices</caption><thead><tr>{["Tender", "Location", "Published", "Deadline", "Status", "Notice"].map(heading => <th key={heading} scope="col">{heading}</th>)}</tr></thead><tbody>{visible.length ? visible.map(notice => <tr key={notice.id}><th scope="row">{notice.title}</th><td>{notice.location}</td><td>{notice.published}</td><td>{notice.deadline}</td><td>{notice.status}</td><td><a href={notice.noticeUrl}>View notice <HiArrowUpRight aria-hidden="true" /></a></td></tr>) : <tr><td colSpan={6}><OpportunityEmpty title={`No ${status === "All" ? "published" : status.toLowerCase()} tender notices`} text="Notices will appear here when available. Review the procurement guidance to prepare for future opportunities." /></td></tr>}</tbody></table></div> : visible.length ? <div className="op-card-grid">{visible.map(notice => <article className="op-card" key={notice.id}><span className="op-badge">{notice.status}</span><h3>{notice.title}</h3><p>{notice.location}</p><dl><div><dt>Published</dt><dd>{notice.published}</dd></div><div><dt>Deadline</dt><dd>{notice.deadline}</dd></div></dl><a href={notice.noticeUrl}>View notice <HiArrowUpRight aria-hidden="true" /></a></article>)}</div> : <OpportunityEmpty title={`No ${status.toLowerCase()} tenders at the moment`} text={status === "Open" ? "New procurement opportunities will be published here with their scope, documents and submission dates." : "Closed notices will remain available here for reference once tenders have been published."} />}<div className="op-list-footer"><p aria-live="polite">Showing {visible.length} of {filtered.length} {status === "All" ? "published" : status.toLowerCase()} notices</p>{!archive && <Link className="op-inline-link" to="/tenders/all">View all tenders <HiArrowUpRight aria-hidden="true" /></Link>}</div></div></section>
    <PublicFooter /></main>;
}
